# app.py
from flask import Flask, Response
from video_processing import generate_frames

app = Flask(__name__)

@app.route('/video_feed')
def video_feed():
    # Return the video feed generated by generate_frames()
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(debug=True)
